<a href="https://colab.research.google.com/github/Le2se0hy/FA_ProAn/blob/main/%ED%95%B8%EC%A6%88%EC%98%A8%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_2%EC%9E%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 핸즈온 머신러닝_2장

0112(월) - p.68(2.1) ~ p.82(2.3.5)

0113(화) - p.82(2.3.6) ~ p.88(사이킷런 전까지)

0114(수) - p.88 ~ p.92 (2.3 완료)

0115(목) - p.92 ~ p.99 (2.4.2 완료)

0116(금) - p.99 ~ p.103 (tip까지 완료)

0119(월) - p.103 ~ p.106

0120(화) - p.106 ~ p.108

---
## 2.1 실제 데이터로 작업하기

---
## 2.2 큰 그림 보기

### 2.2.1 문제 정의

- 다중 회귀 : 회귀 문제 중 예측에 사용할 특성이 여러 개인 경우
- 단변량 회귀 : 각 구역마다 하나의 값을 예측하는 경우
- 다변량 회귀 : 구역마다 여러 개의 값을 예측하는 경우

### 2.2.2 성능 측정 지표 선택

**평균 제곱근 오차 (RMSE)**

![](https://drive.google.com/uc?id=18qZl7lGfIWP5iuA--uG8i2_rPGUrwRLl)

만약 이상치로 보이는 구역이 많으면 **평균 절대 오차 (MAE)**를 고려해봐야함

$MAE(𝐗,h) = 1/m \Sigma_{i=1}^m k |h(x^i)-y^i|$

RMSE와 MAE 모두 예측값의 벡터와 타깃값의 벡터 사이의 거리를 재는 방법임. 거리 측정에는 노름Norm*을 사용할 수 있음
- 유클리드 노름 : 제곱항을 합한 것의 제곱근(RMSE). $l_2$ 노름
- 맨해튼 노름 : 절댓값의 합을 계산. $l_1$ 노름
- 일반적으로 원소가 n개인 벡터 v의 $l_k$ 노름은 각 벡터의 k제곱의 합의 k분의 1 제곱으로 정의

노름의 지수가 클수록 큰 값의 원소에 치우치며 작은 값은 무시됨.
-> RMSE가 MAE보다 조금 더 이상치에 민감함

#### *노름의 정의*

**노름Norm**이란 **벡터가 얼마나 큰가?** 를 재는 기준이다

$||x||$는 벡터 $x$의 크기이다 !

노름은 다음과 같은 규칙들을 만족해야한다

① 양의 정부호성
- $||x|| ≥ 0$
- $||x|| = 0 → x=0$
- 크기가 항상 0 이상이며 크키가 0일 경우엔 해당 벡터는 영벡터임

② 동차성
-  $||αx|| = |α| ||x||$
- 벡터를 α배 늘리면 크기도 |α|배 늘어남

③ 삼각부등식
- $|| x+y || ≤ ||x|| + ||y||$
- 두 벡터를 더한 길이는 각각의 길이의 합보다 크지않음




### 2.2.3 가정 검사



---
## 2.3 데이터 가져오기

### 2.3.1 구글 코랩을 사용하여 예제 코드 실행하기

### 2.3.2 코드와 데이터 저장하기

### 2.3.3 대화식 환경의 편리함과 위험

### 2.3.4 책의 코드와 노트북의 코드

### 2.3.5 데이터 다운로드



In [2]:
from pathlib import Path  # Path : 파일/폴더 경로를 다루기 쉽게 해주는 객체
import pandas as pd  # pandas : 데이터를 처리하고 분석해주는 라이브러리
import tarfile  # tarfile : tar파일의 압축 형식을 지원하며 압축, 해제, 파일 추가, 목록 확인 등 다양한 작업을 함
import urllib.request  # urllib.requeest : url을 열고 읽는 표준 라이브러리

def load_housing_data():  # def로 load_housing_data라는 함수를 정의
  tarball_path = Path("datasets/housing.tgz")  # datasets라는 폴더 밑에 housing.tgz라는 파일의 경로를 준비함
                                               # tarball_path는 그 경로를 가르키는 객체임
  if not tarball_path.is_file():  # .is_file을 통해 housing.tgz가 로컬에 있는지 확인. 없으면 다운로드 및 압축해제함
    Path("datasets").mkdir(parents=True, exist_ok=True)  # mkdir로 datasets라는 폴더를 만듬
                           # parents=True : datasets의 상위 경로가 주어졌을 경우 만들어줌
                           # exist_ok=True : datasets라는 폴더가 있을 경우, 에러가 안남. 해당 옵션이 없을 경우 FileExistsError가 남

    url = "https://github.com/ageron/data/raw/main/housing.tgz"  # 다운로드할 파일의 url을 문자열로 저장
    urllib.request.urlretrieve(url, tarball_path)  # urlretrieve로 url에 접속 후 파일을 다운로드 받고 tarball_path 위치에 저장
    with tarfile.open(tarball_path) as housing_tarball:  # tarfile.open으로 tarball_path를 열어서 housing_tarball이라는 핸들을 만든다.
                                                        # 여기서 housing_tarball은 tar 내부 파일 목록을 읽고, 꺼내고, 추출할 수 있는 객체가 됨
      housing_tarball.extractall(path="datasets")  # tar파일 안에 압축된 파일들을 모두 압축해제해서 datasets라는 폴더에 풀어줌
  return pd.read_csv(Path("datasets/housing/housing.csv"))  # 압축을 풀고 나면 생기는 housing.csv를 pandas로 읽어서 DataFrame으로 만들어서 반환함

housing = load_housing_data()  # 함수 실행 후 마지막 줄에 return값을 housing변수에 저장

/tmp/ipython-input-3728936072.py:18: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  housing_tarball.extractall(path="datasets")  # tar파일 안에 압축된 파일들을 모두 압축해제해서 datasets라는 폴더에 풀어줌


### 2.3.6 데이터 구조 훑어보기

- head() : 처음 5개의 행을 출력. 괄호 속 숫자로 개수 지정 가능
- info() : 데이터에 관한 간략한 설명 출력. 전체 행수, 각 특성의 데이터 타입, null이 아닌 값의 개수 ...
- value_counts() : 어떤 카테고리가 있고 각 카테고리마다 얼마나 많은 구역이 있는지 출력.
- describe() : 숫자형 특성의 요약 정보를 보여줌.
- hist() : 숫자형 특성에 대한 히스토그램 출력


### 2.3.7 테스트 세트 만들기

- **데이터 스누핑 편향** : 어떤 테스트 세트를 들여다봤을때 겉으로 드러난 어떤 패턴에 속아 특정 머신러닝 모델을 선택하게 되고, 그 테스트 세트로 일반화 오차를 추정하게 되면 매우 낙관적인 추정이 되어 기대한 성능이 나오지 않는 경우

- 테스트 세트 만들기

In [ ]:
import numpy as np

def shuffle_and_split_data(data, test_ratio):  # def로 함수 정의. 데이터셋과 테스트 세트의 비율을 매개변수로 선언
  shuffled_indices = np.random.permutation(len(data))  # 데이터 행의 개수까지의 숫자를 무작위로 섞은 배열을 변수에 넣음 (인덱스만 섞음)
  test_set_size = int(len(data) * test_ratio)  # 테스트 세트의 크기 계산 : 데이터 개수 * 테스트 세트 비율
  test_indices = shuffled_indices[:test_set_size]  # 무작위로 섞인 인덱스 중에 위에서 설정한 테스트 세트의 크기만큼의 앞부분을 테스트 세트로 사용함
  train_indices = shuffled_indices[test_set_size:]  # 나머지를 훈련 세트로 사용함
  return data.iloc[train_indices], data.iloc[test_indices]  # 각 훈련세트와 테스트세트의 데이터를 두개의 튜플로 반환함
                                                            # iloc : 인덱스의 위치로 해당 데이터를 추출하는 인덱싱 방법

위의 방법도 좋지만 알고리즘이 계속하여 전체 데이터셋을 봐야함

해결방법 :
- 처음 실행에서 테스트 세트를 저장하고 다음번 실행에서 불러들임
- 항상 같은 난수 인덱스가 생성되도록 np.random.permutation()을 호출하기 전에 난수 발생기의 초깃값을 괄호 속에 지정

위의 방법들은 다음번에 업데이트된 데이터셋을 사용할 때 문제가 됨

-> 샘플의 식별자를 사용하여 테스트 세트로 보낼지 말지 정함. 샘플이 고유하고 변경 불가능한 식별자를 가지고 있다고 가정.

예를 들어 각 샘플마다 식별자의 해시값을 계산하여 해시 최댓값의 20%보다 작거나 같은 샘플만 테스트 세트로 보낼 수 있음

In [ ]:
from zlib import crc32  # zlib라이브러리에서 crc32는 데이터를 32비트 정수로 해시처럼 바꿔주는 함수. 같은 입력이면 항상 같은 결과.

def is_id_in_test_set(identifier, test_ratio):  # 해당 ID가 테스트 세트에 들어가는지를 판단하는 함수 정의. 각 샘플의 고유 ID와 테스트 비율을 매개변수로 선언
  return crc32(np.int64(identifier)) < test_ratio * 2**32  # crc32(np.int64(identifier))로 0~2^32-1 범위의 값을 만들고 그 값이
                                                           # 그 값이 test_ratio * 2^32 보다 작으면 테스트 세트에 넣음

def split_data_with_id(data, test_ratio, id_column):  # 데이터를 훈련세트와 테스트세트로 나누는 함수 정의. 데이터, 테스트비율, id가 들어있는 컬럼을 매개변수로 선언함
  ids = data[id_collumn]  # 데이터에서 id_collumn만 꺼내서 ids라는 변수에 넣음
  in_test_set = ids.apply(lambda id_: is_id_in_test_set(id_, test_ratio))  # 각 아이디에 is_id_in_test_set 함수를 적용해서 각 행이 테스트인지 아닌지에 대한 불리언 시리즈를 만듬
  return data.loc[~in_test_set], data.loc[in_test_set]  # data.loc[]은 대괄호 속의 조건이 True인 행만 선택함
         # 조건에 ~로 True와 False를 뒤집어서 훈련세트 선택
                                 # 테스트 세트 선택


예시로 주택 데이터셋에서는 식별자 컬럼이 없음 -> 행의 인덱스를 id로 사용해서 해결


In [ ]:
housing_with_id = housing.reset_index()  # 인덱스 열이 추가된 데이터 프레임이 반환됨
train_set, test_set = split_data_with_id(housing_with_id, # 분할할 데이터
                                         0.2, # 테스트 비율
                                         "index")  # id로 쓸 컬럼

                                        # split_data_with_id 함수를 써서 index 컬럼을 기준으로 항상 같은 규칙으로 80% 훈련세트 / 20% 테스트세트로 나눔

행의 인덱스를 고유 식별자로 사용할 때 새 데이터는 데이터셋의 끝에 추가되어야 하고 어떤 행도 삭제되어서는 안됨

-> 불가능 할 땐 고유 식별자를 만드는데 안전한 특성을 사용해야함

예 ) 구역의 위도와 경도

In [ ]:
housing_with_id["id"] = housing["longitude"] * 1000 + housing["latitude"]  # 경도가 float값으로 충돌을 막기위해 1000을 곱하여 위도랑 더하여 id로 만듬
train_set, test_set = split_data_with_id_hash(housing_with_id, 0.2, "id")  # 위의 코드와 해석이 같음

사이킷런은 데이터셋을 여러 섯브셋으로 나누는 다양한 방법을 제공함 → train_test_split 함수

train_test_split 함수의 특징
- shuffle_and_split (*2.3.7 테스트 세트 나누기 코드) 함수와 매우 유사함
- random_state 매개변수 : 난수 초깃값을 지정할 수 있음
- 행의 개수가 같은 여러 개의 데이터셋을 넘겨서 동일한 인덱스를 기반으로 나눌 수 있음

In [ ]:
from sklearn.model_selection import train_test_split  # 사이킷런 라이브러리의 model_selection 모듈에서 train_test_split 함수를 가져옴

train_set, test_set = train_test_split(housing,  # 훈련세트와 테스트세트로 분할할 원본 데이터
                                       test_size=0.2,  # 테스트 비율. 훈련세트는 데이터의 80%, 테스트세트는 20%가 됨
                                       random_state=42)  # 랜덤 시드를 고정. 같은 데이터에 같은 랜덤시드를 사용하면 매번 실행해도 똑같은 분할 결과가 나옴. 아무 정수나 가능.

# train_test_split은 기본적으로 shuffle=True라서 데이터를 섞고 나누는데 시계열 데이터와 같이 순서가 중요한 경우엔 shuffle = False를 고려해야함

**계층적 샘플링** :

순수한 랜덤 샘플링 방식에서 데이터셋이 특성수에 비해 충분히 크지않다면 샘플링 편향이 생길 가능성이 큼

샘플링 편향을 막기 위해 모델에서 중요한 특성은 계층별로 데이터셋에 충분한 샘플 수가 있어야함 → 계층의 중요도를 추정하는데 편향을 방지하기 위해서


예) 전문가가 중간 소득이 중간 주택 가격을 예측하는데 매우 중요하다고 함. 우선 중간 소득이 연속적인 숫자형 특성이므로 소득에 대한 카테고리 특성을 만듬

In [ ]:
housing["income_cat"] = pd.cut(housing["median_income"],  # housing 데이터에 "income_cat"이라는 새 범주형 특성을 만듬. pd.cut()는 연속형 숫자 데이터를 구간으로 나눠서 범주형으로 바꾸는 함수
                                                          # median_income을 입력으로 이 데이터를 범주형으로 바꿀거임
                               bins=[0, 1.5, 3.0, 4.5, 6., np.inf]  # bins: 경계값들. 구간을 나누는 칸막이 역할. 6개의 경계값으로 구간은 5개가 만들어짐. (0, 1.5],(1.5, 3.0],...(6.0, ∞]로 나눠짐
                               labels=[1, 2, 3, 4, 5])  # 각 구간에 라벨 지정. 첫 번째 구간 (0, 1.5] → 1, (1.5, 3.0] → 2,... income_cat은 1~5 사이의 값만 가지는 범주형 변수


In [ ]:
# 위에서 만든 income_cat 소득 카테고리 히스토그램 출력

housing["income_cat"].value_counts().sort_index().plot.bar(rot=0, grid=True)
# .value_counts() : 각 값이 몇 번 등장하는지 빈도를 셈. 기본적으로 빈도 내림차순으로 정렬
# .sort_index() : 위에서 나온 결과를 인덱스 기준으로 정렬
# .plot.bar() : 막대 그래프 그리기
# rot=0 : x축 라벨(=여기선 카테고리값) 글씨 회전 각도. 0이면 회전 안 함(수평)
# grid=True : 그래프에 격자 표시

plt.xlabel("소득 카테고리")  # x축 라벨(아래쪽 제목)을 "소득 카테고리"로 설정. 1,2,3,4,5 와 같은 값이 있음
plt.ylabel("구역 개수")  # y축 라벨(왼쪽 제목)을 “구역 개수”로 설정. y축 값은 value_counts()로 센 샘플 개수
plt.show()  # 그래프 출력

split() 메서드는 훈련과 테스트 데이터 자체가 아닌 인덱스를 반환함. 여러 개로 분할 시 모델의 성능을 더 잘 추정할 수 있음



In [ ]:
# 한 데이터셋으로 각각 다른 10개의 계층 분할을 생성

from sklearn.model_selection import StratifiedShuffleSplit  # 사이킷런의 계층적 분할 전용 클래스

splitter = StratifiedShuffleSplit(n_splits=10,  # splitter 객체 생성.  # n_splits=10 : 10번 서로 다른 분할을 생성
                                  test_size=0.2,  # 테스트 비율
                                  random_state=42)  # 랜덤성 고정
strat_splits = []  # 빈 리스트 만듬

for train_index, test_index in splitter.split(housing, housing["income_cat"]):
# splitter에게 housing 데이터를 train/test로 나눌 건데, income_cat의 비율은 train과 test에서도 비슷하게 유지해줘.” 라고 요청하고,
# splitter가 만들어 준 (train 인덱스들, test 인덱스들) 을 한 번에 하나씩 받아서 10번 반복
# split()은 행 번호로 리스트를 두 개 만듬. train_index : train으로 보낼 행 번호들의 배열, test_index : test로 보낼 행 번호들의 배열 (eg. train_index = [0, 2, 3..], test_index = [1, 6])

  strat_train_set_n = housing.iloc[train_index]  # housing에서 train_index에 해당하는 행들만 골라 새로운 데이터프레임(훈련 세트)으로 만듬
  strat_test_set_n = housing.iloc[test_index]  # 위와 같음 (테스트세트)
  # iloc : 인덱스의 위치로 해당 데이터를 추출하는 인덱싱 방법

  strat_splits.append([strat_train_set_n, strat_test_set_n])  # 10번 분할한 결과를 전부 쌍(train/test)으로 저장함
  # strat_splits[0] = [train_df_1, test_df_1]
  # strat_splits[1] = [train_df_2, test_df_2]
  # ...
  # strat_splits[9] = [train_df_10, test_df_10] 와 같이 저장됨


계층적 샘플링은 자주 사용되기 때문에 하나의 분할이 필요한 경우엔 train_test_split()함수와 stratify 매개변수를 사용하여 간편하게 만듬

In [ ]:
train_set, test_set = train_test_split(housing, test_size=0.2, random_state=42, stratify=housing["income_cat"])
                                                                                # stratify='원본데이터'["데이터에서 비슷한 비율로 들어가길 바라는 범주의 변수명"]

*책에서 앞으로 income_cat 특성을 사용하지 않을거기 때문에 열을 삭제하고 원래 상태로 되돌림*

*코드를 직접 돌리는건 아니지만 열 삭제 및 원상 복구 코드를 배우기 위해 밑에 설명함*

In [ ]:
for set_ in (strat_train_set, strat_test_set):  # strat_train_set와 strat_test_set을 튜플로 묶어서 똑같은 작업을 하겠다는 뜻
                                                # set_ : 반복문에서 쓰는 임시변수로, set은 파이썬 내장 타입 이름이라 덮어쓰지 않으려고 _를 붙임
  set_.drop("income_cat",  # 삭제할 컬럼 이름.  # .drop() : 행이나 열 삭제할때 사용
            axis=1,  # 열column기준으로 삭제. axis=0 → 행(row), axis=1 → 열(column)
            inplace=True)  # inplace=True : 원본 DataFrame을 직접 수정

---
## 2.4 데이터 이해를 위한 탐색과 시각화

2.4에서는 훈련세트에 대해서만 탐색함. 훈련 세트가 매우 크다면 탐색 단계에서 조작을 간단하고 빠르게 하기 위해 탐색을 위한 세트를 별도로 샘플링할 수도 있음.

housing = strat_train_set.copy() 로 나중에 훈련 세트가 변환을 실험할때 되돌릴 수 있도록 원본 데이터의 복사본을 만듬


### 2.4.1 지리적 데이터 시각화하기

- 데이터셋에서 지리 정보(위도와 경도)가 포함되어있어 모든 구역을 산점도로 만들어 데이터를 시각화

In [ ]:
housing.plot(kind="scatter", x="longtitude", y="latitude", grid=True)
             # 산점도 형태로   x축을 경도 컬럼으로  y축을 위도 컬럼으로 격자표시 있게
plt.xlabel("경도")  # x축은 경도라고 표시
plt.ylabel("위도")  # y축은 위도라고 표시
plt.show()  # 그래프 출력

alpha 옵션을 0.2로 주면 데이터 포인트가 밀집된 영역을 잘 보여줌

In [ ]:
housing.plot(kind="scatter", x="longtitude", y="latitude", grid=True, alpha=0.2)
plt.xlabel("경도")                                             # alpha : 투명도를 0.2로 지정하여 밀집될수록 진해짐
plt.ylabel("위도")
plt.show()

조금 더 두드러진 패턴을 보려면 매개변수를 다양하게 조절해봐야함

- 원의 반지름 : 매개변수 s
- 색상 (가격을 나타냄) : 매개변수 c

- → 미리 정의된 컬러맵 중 파란색(낮은 가격)에서 빨간색(높은 가격)까지의 범위를 가지는 jet를 사용 : 매개변수 cmap

In [ ]:
housing.plot(kind="scatter", x="longtitude", y="latitude", grid=True,
             s=housing["population"]/100,  # s : 원의 크기. population이 클수록 점이 커져서, 인구가 밀집된 곳이 튀어나와 보임. /100 : 원래 숫자는 너무 커서 보기 좋은 크기로 줄임
             label="인구",  # label="인구" : 점 크기가 인구라는걸 범례에 표시
             c="median_house_value",  # c : 점의 색을 결정하는 값. median_house_value 컬럼 사용
             cmap="jet",  # cmap : 컬러맵. jet : 파랑 → 초록 → 노랑 → 빨강 식으로 변하는 컬러맵이라
             colorbar=True,  # 오른쪽에 색상-값 대응표를 자동으로 붙임.
             legend=True,  # 범례 표시
             figsize=(10,7))  # 그림 크기 지정
cax=plt.gcf().get_axes()[1]  # .gcf() : 그려진 figure을 가져옴. .get_axe() : Figure 안에 들어있는 축 객체들 리스트를 가져옴
                             # 현재 figure 안에서 축은 1.메인 산점도 축  2.컬러바 축
                             # get_axes()[0] → 산점도 메인 축 /  get_axes()[1] → 컬러바 축
cax.set_ylabel("중간 주택 가격")  # 컬러바 축의 y라벨을 설정
plt.xlabel("경도")  # 위와 같음
plt.ylabel("위도")
plt.show()

### 2.4.2 상관관계 조사하기

데이터셋이 너무 크지 않을 때 모든 특성 간의 **표준 상관계수**($r$)를 corr() 메서드를 이용해 계산

상관계수(correlation coefficient) : 두 변수 사이의 선형 관계 강도를 숫자로 표현

값의 범위 : -1 ≤ corr ≤ 1

- 1 :	완벽한 양의 상관관계
- 0	: 선형 관계 없음
- -1 : 완벽한 음의 상관관계

In [ ]:
corr_matrix = housing.corr(numeric_only=True)  # numeric_only=True : housing 데이터에 숫자가 아닌 컬럼도 있어서 숫자형 컬럼만 골라서 상관계수 행렬을 만들게 함

In [ ]:
corr_matrix["median_house_value"].sort_values(ascending=False)
# median_house_value에서 상관계수를 큰 값 → 작은 값 순서로 내림차수로 정렬(ascending=False)

특성 사이의 상관관계를 확인하는 다른 방법은 판다스의 scatter_matrix 함수를 사용해 숫자형 특성 간 산점도를 그리는 것임

In [ ]:
from pandas.plotting import scatter_matrix. # pandas.plotting 모듈 안에 있는 scatter_matrix 함수를 가져옴

attributes = ["median_house_value", "median_income", "total_rooms", "housing_median_age"]  # 산점도 행렬에 넣을 컬럼목록을 리스트로 정의
scatter_matrix(housing[attributes],  # scatter_matrix() : 선택된 변수들로 산점도 행렬을 그림. 여기선 4x4, (행 i, 열 j) 칸에는 x축 = j번째 변수, y축 = i번째 변수 의 산점도가 들어감.
               # housing[attributes] : housing 데이터에서 attributes 리스트에 들어있는 4개 컬럼만 뽑아서 새 데이터프레임을 만듦
               figsize=(12, 8))  # 그림 전체 크기
plt.show

밑과 같은 이미지로 출력됨.

![](https://drive.google.com/uc?id=1fEwVZx6evVvM462xbgdzlm7swIBz-F1W)

대각선 칸에는 보통 히스토그램 또는 커널 밀도 그래프가 들어가서 *해당 변수의 분포*를 보여줌

산점도 행렬을 보면 중간 주택 가격(median_house_value)을 예측하는데 중간 소득(mdain_income)이 가장 유용해 보임. 해당 산점도를 확대했을 때 이미지를 보면

![](https://drive.google.com/uc?id=1-Ur8OhTg0jeu1LV81E5_pqrtGpWnsVOU)

- 1. 상관관계가 매우 강하다. 위쪽으로 향하는 경향을 보여주며 포인트들이 퍼져있지는 않음
- 2. 앞서 본 가격의 한곗값이 500,000에서 수평선으로 잘 보인다. 하지만 이 그래프에는 직선에 가까운 형태가 더 나타나고 450,000, 350,000, 280,000에서도 같은 형태가 보인다. → 알고리즘이 데이터에서 이런 이상한 형태를 학습하지 않도록 해당 구역을 제거할 수 있음

### 2.4.3 특성 조합으로 실험하기

어떤 특성의 분포는 오른쪽 꼬리가 길어서 데이터를 변형하는 것이 좋을 수 있음. (예를 들면 로그 함수나 제곱근을 적용)

머신러닝 알고리즘용 데이터를 준비하기 전에 마지막으로 여러 가지 특성을 조합한다.

In [ ]:
housing["rooms_per_house"] = housing["total_rooms"] / housing["households"]
housing["bedrooms_per_room"] = housing["total_bedrooms"] / housing["total_rooms"]
housing["population_per_house"] = housing["population"] / housing["households"]

In [ ]:
corr_matrix = housing.corr(numeric_only=True)
corr_matrix["median_house_value"].sort_values(ascending=False)  # 2.4.2의 코드 주석과 같음

"""
결과
> median_house_value  1.000000
median_income  0.688380
rooms_per_house  0.143663
total_rooms  0.137455
...
"""

이 탐색 단계는 완벽하지 않지만 빠르게 시작하여 인사이트를 얻는 것이 합리적인 첫번째 프로토타입을 만드는 데 도움이 된다. 이 과정을 반복하여 프로토타입을 만들고 실행한 후 그 결과를 분석해서 더 많은 인사이트를 얻고 다시 이 탐색 단계로 돌아오게 됨.

---
## 2.5 머신러닝 알고리즘을 위한 데이터 준비

머신러닝 알고리즘을 위해 데이터를 준비는 함수를 만들어 자동화해야 함
- 어떤 데이터셋에 대해서도 데이터 변환을 손쉽게 반복할 수 있음
- 향후 프로젝트에 재사용 가능한 변환 라이브러리를 점진적으로 구축할 수 있음
- 실제 시스템에서 알고리즘에 새 데이터를 주입하기 전에 이 함수를 사용해 변환할 수 있음
- 여러 가지 데이터 변환을 쉽게 시도해볼 수 있고 어떤 조합이 가장 좋은지 확인하는 데 편리함

In [ ]:
housing = strat_train_set.drop("median_house_value", axis=1)  #.drop() : 데이터 복사본을 만들어 반환
housing_labels = strat_train_set["median_house_value"].copy()

# strat_train_set를 다시 복사해서 원래 훈련 세트로 복원하고
# 예측 변수와 타깃값에 같은 변형을 적용하지 않기 위해 예측 변수와 레이블을 분리함

### 2.5.1 데이터 정제

대부분의 머신러닝 알고리즘은 누락된 특성을 다루지 못하므로 처리할 수 있는 함수를 만들거임

앞서 total_bedrooms 특성에 값이 없는 경우를 보았는데 *(어디서 나왔는지 기억이 나지않음)* 이를 고치는 방법으론
- 1. 해당 구역을 제거
- 2. 전체 특성을 삭제
- 3. 누락된 값을 어떤 값(0, 평균, 중간값 등)으로 채움 = "대체"

판다스 데이터프레임의 dropna(), drop(), fillna() 메서드를 사용해서 처리

In [ ]:
# .dropna() : total_bedrooms 컬럼에서 결측치가 있는 행들을 삭제
housing.dropna(subset=["total_bedrooms"], inplace=True)  # subset : 해당 컬럼 기준으로만 결측치 검사. inplace=True : 삭제 결과를 housing에 바로 반영. 원본 자체가 바뀜.(False:새 데이터프레임 반영)
# 데이터가 더 깨끗해지지만 데이터 수가 줄어듦 -> 결측치가 많으면 학습 데이터가 너무 줄어 성능이 떨어질 수 있음.

# .drop() : 해당 컬럼 자체를 삭제
housing.drop("total_bedrooms", axis=1, inplace=True)  # axis=1 : 열 삭제(행 삭제는 axis=0)  inplace=True : housing에 즉시 반영

# .fillna() : 결측치를 중앙값으로 채우기
median = housing["total_bedrooms"].median()  # 결측치를 제외하고 중앙값을 계산
housing["total_bedrooms"].fillna(median, inplace=True)  # NaN인 곳을 median 값으로 채움
# 중앙치를 사용하는 이유는 평균보다 안정적이기 때문이다.

옵션3인 fillna() 방식이 데이터를 최대한 유지하기 때문에 해당 방식을 선택한다. 하지만 이 코드 대신 사이킷런에 있는 편리한 SimpleImputer 클래스를 사용함. → 각 특성의 중간값을 저장할 수 있어 유용. 훈련 세트뿐만 아니라 검증 세트와 테스트 세트, 모델에 주입될 새로운 데이터에 있는 누락된 값도 대체 가능

In [ ]:
from sklearn.impute import SimpleImputer

# 누락된 값을 특성의 중간값으로 대체하도록 지정해서 객체 생성
imputer = SimpleImputer(strategy="median")

# 중간값은 수치형 특성에서만 계산될 수 있기 때문에 수치 특성만 가진 데이터 복사본을 생성
housing_num = housing.select_dtypes(include=[np.number])  # .select_dtypes() : 데이터타입을 기준으로 컬럼 선택
                                                          # include=[np.number] : np.number은 모든 숫자형타입을 포함. 숫자형 해석만 가능한 컬럼포함

# .fit() 함수를 사용해서 housing_num의 각 숫자 컬럼에 대해 중앙값을 계산해서 imputer 내부에 저장
imputer.fit(housing_num)  # 데이터 변형 단계가 아닌 중앙값만 계산함 !!

# imputer는 중간값 계산 결과를 객체의 statics_ 속성에 저장
imputer.statics_
# 출력값 : array([-118.51, 34.26, 29. , 2125. , 434. , 1167. , 488. , 3.5385])
housing_num.median().values
# 출력값 : array([-118.51, 34.26, 29. , 2125. , 434. , 1167. , 488. , 3.5385])

# 학습된 imputer 객체를 사용해 훈련 세트에서 누락된 값을 학습한 중간값으로 바꿀 수 있음
X = imputer.transform(housing_num)  # .transform() : 누락된 값


누락된 값을 평균(strategy="mean"), 최빈값(strategy="most_frequent"), 상수(strategy="constant", fill_vale=...)로 바꿀 수도 있음. 최빈값과 상수는 수치가 아닌 데이터도 지원함.

*sklearn.impute 패키지는 누락된 값을 대체하기 위해 강력한 클래스를 제공함*
- *KNNImputer : 누락된 값을 이 특성에 대한 k-최근접 이웃의 평균으로 대체 거리는 모든 특성을 바탕으로 계산*
- *IterativeImputer : 특성마다 회귀 모델을 훈련하여 다른 모든 특성을 기반으로 누락된 값을 예측. 그다음 업데이트 된 데이터로 모델을 다시 훈련하고 이 과정을 몇 번 반복하여 모델과 대체 값을 향상시킴*


사이킷런 변환기는 판다스 데이터프레임이 입력되더라도 넘파이 배열을 출력

→ imputer.transform(housing_num)의 출력은 넘파이 배열임

X에는 열 이름도 인덱스도 없음. X를 데이터프레임으로 감싸서 housing_num으로부터 열 이름과 인덱스를 복원하는 것은 어렵지 않음

housing_tr = pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)

In [ ]:
housing_tr = pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)

### 2.5.2 텍스트와 범주형 특성 다루기

해당 부분에서는 텍스트 특성을 다룸.

이 데이터셋에는 ocean_proximity만 있음. 처음 몇 개 샘플에서 이 특성값을 확인해보자면

In [ ]:
housing_cat = housing[["ocean_proximity"]]
housing_cat.head(8)

# >>>   ocean_proximity
# 13096        NEAR BAY
# 14973       <1H OCEAN
# 3785           INLAND
# 14689          INLAND
# ...

이는 임의의 텍스트가 아닌 가능한 값을 제한된 개수로 나열한 것이고 각 값은 카테고리를 나타냄.

따라서 이 특성은 범주형 특성인데 대부분의 머신러닝 알고리즘은 숫자를 다루므로 이 카테고리를 텍스트에서 숫자로 변환해야함.

→ 이를 위해 사이킷런의 OrdinalEncoder 클래스를 사용함

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)

# housing_cat_encoded에 인코딩된 몇 개의 값을 확인하면 다음과 같음
housing_cat_encoded[:8]
# >>> array([[3,], [0,], [1,], [1,], [4,], [1,], [0,], [3,]])

categories_ 인스턴스 변수를 사용해 카테고리 리스트를 얻음.

범주형 특성마다 ID 카테고리 배열을 담은 리스트가 반환됨. (이 경우는 범주형 특성이 하나만 있으므로 배열 하나를 담은 리스트가 반환됨)


In [ ]:
ordinal_encoder.categories_
# >>> [array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
#      dtype=object)]

이 표현 방식의 문제는 머신러닝 알고리즘이 가까이 있는 두 값을 떨어져 있는 두 값보다 더 비슷하다고 생각한다는 점이다.

일부 경우엔 괜찮지만 ocean_proximity 열에는 해당되지 않음.

이러한 문제는 일반적으로 카테고리별 이진 특성을 만들어 해결

⇒ **원-핫인코딩** : 카테고리가 '<1H OCEAN'일 때 한 특성이 1이고 그 외 특성은 0, 카테고리가 'INLAND'일 때 다른 한 특성이 1이 되고 그 외는 0이 되는 식

- 더미특성 : 새로운 특성

사이킷런은 범주의 값을 원-핫 벡터로 바꾸기 위한 OneHotEncoder 클래스를 제공함

In [ ]:
from sklearn.processing import OneHotEncoder

cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)

보통 OneHotEncoder의 출력은 넘파이 배열이 아닌 사이파이 희소 행렬이다.

- 넘파이 배열 : 빈칸이란 개념 없이 모든 요소와 행과 열을 다 저장한다.

[1 0 0 0]

[0 0 0 0]

[0 0 2 0]


- 희소 행렬 : 0은 저장하지 않음.

(0행, 0열) = 1

(2행, 2열) = 2


원-핫 인코딩은 행마다 하나만 1이고 나머지는 0으로 채워진 매우 큰 행렬을 만드는데 이런 경우에 희소 행렬이 필요함.




In [ ]:
housing_cat_1hot

# <16512x5 sparse matrix of type '<class 'numpy.float63'>'
# with 16512 stored elements in Compressed Sparse Row format

- toarray() : 대부분은 희소행렬을 보통의 2D 배열처럼 사용할 수 있지만 밀집된 넘파이 배열로 바꾸기 위해 호출해야하는 메서드

In [ ]:
housing_cat_1hot.toarray()

# array([[0., 0., 0., 1., 0.],
#       [1., 0., 0., 0., 0.],
#       [0., 1., 0., 0., 0.],
#       ...,
#       [0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0.],
#       [0., 0., 0., 0., 1.]])

또는 OneHotEncoder를 만들때 sparse=False (or sparse_output=False)로 설정하여 transform() 메서드가 일반적이 넘파이 배열을 반환하게 할 수 있음

OrdinalEncoder처럼 인코더의 categories_ 인스턴스 변수를 사용해 카테고리 리스트를 얻을 수 있음

In [ ]:
cat_encoder.categories_

# [array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'], dtype=object)]

- get_dummies() : 판다스에는 범주형 특성을 원-핫 표현으로 바꿔서 카테고리마다 하나의 이진 특성을 만드는 함수

In [ ]:
df_test = pd.DataFrame({"ocean_promixity": ["INLAND", "NEAR BAY"]})
pd.get_dummies(df_test)

# ocean_proximity_INLAND ocean_proximity_NEAR BAY
#0                     1                        0
#1                     0                        1

OneHotEncoder의 장점은 어떤 카테고리로 훈련되었는지 기억한다는 점이다. → 모델을 제품에 적용할 때 훈련과 완전히 동일한 특성이 주입되어야 하기 때문에 매우 중요함

cat_encoder를 (fit_transform()이 아니라 transform()으로) df_test에 적용했을 때 어떻게 출력되는지 밑에서 확인.

In [ ]:
cat_encoder.transform(df_test)
# array([[0., 1., 0., 0., 0.],
#       [0., 0., 0., 1., 0.]])

- get_dummies() : 두 개의 카테고리만 보았기 때문에 두개 열만 출력. "<2H OCEAN"와 같은 알 수 없는 카테고리를 담은 데이터프레임을 get_dummies()에 주입하면 아무런 문제없이 변환된 결과를 출력함.
- OneHotEncoder : 학습된 카테고리마다 하나의 열을 순서대로 출력